# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='Date_of_manu',
        ),
    ]
