# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productDetails', '0002_remove_productdetails_date_of_manu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='category_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productDetails.Category'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='manufacturer_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productDetails.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='rack_No',
            field=models.IntegerField(null=True),
        ),
    ]
